apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: api-slo-alerts
  namespace: demo
  labels:
    release: kube-prometheus-stack
spec:
  groups:
  - name: api-slo.rules
    rules:
    - alert: ApiSuccessRateLow
      expr: sum(rate(flask_http_request_total{namespace="demo",status!~"5.."}[2m])) / sum(rate(flask_http_request_total{namespace="demo"}[2m])) < 0.95
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "API Success Rate is low"
        description: "The API success rate has dropped below 95%. Current value is {{ $value }}."
