apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.1.1
    helm:
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
        alertmanager:
          enabled: true
          config:
            route:
              group_by: ['alertname']
              group_wait: 10s
              group_interval: 10s
              repeat_interval: 1h
              receiver: 'webhook-receiver'
            receivers:
            - name: 'null'
            - name: 'webhook-receiver'
              webhook_configs:
              - url: 'http://alert-mailer.monitoring.svc.cluster.local:8080/alert'
                send_resolved: true
        grafana:
          enabled: true
        prometheus-node-exporter:
          enabled: false
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
